[versions]
kotest = "5.4.2"
kotlin = "1.7.10"
mockito = "4.8.0"
logback = "1.4.0"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-stdlib-reflect", version.ref = "kotlin" }
kotest-junit5-jvm = { module = "io.kotest:kotest-runner-junit5-jvm", version.ref = "kotest" }
kotest-assertions-core-jvm = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "kotest" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
github-api = "org.kohsuke:github-api:1.308"
unirest = "com.mashape.unirest:unirest-java:1.4.9"
json = "org.json:json:20220320"
org-eclipse-jgit = "org.eclipse.jgit:org.eclipse.jgit:6.3.0.202209071007-r"
commons-io = "commons-io:commons-io:2.11.0"
slf4j-api = "org.slf4j:slf4j-api:2.0.0"
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logback-core = { module = "ch.qos.logback:logback-core", version.ref = "logback" }
mockk = "io.mockk:mockk:1.12.7"

[bundles]
kotlin-testing = [ "kotest-junit5-jvm", "kotest-assertions-core-jvm", "mockito-core" ]

[plugins]
dokka = "org.jetbrains.dokka:1.7.10"
gitSemVer = { id = "org.danilopianini.git-sensitive-semantic-versioning", version = "0.3.0" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-qa = { id = "org.danilopianini.gradle-kotlin-qa", version = "0.25.0" }
multiJvmTesting = { id = "org.danilopianini.multi-jvm-test-plugin", version = "0.4.9" }
publishOnCentral = { id = "org.danilopianini.publish-on-central", version = "2.0.6" }
taskTree = { id = "com.dorongold.task-tree", version = "2.1.0" }
