[versions]
kotest = "5.7.1"
kotlin = "1.9.10"
mockito = "5.5.0"
logback = "1.4.11"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotest-junit5-jvm = { module = "io.kotest:kotest-runner-junit5-jvm", version.ref = "kotest" }
kotest-assertions-core-jvm = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "kotest" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
clikt = "com.github.ajalt.clikt:clikt:3.5.4"
github-api = "org.kohsuke:github-api:1.316"
unirest = "com.mashape.unirest:unirest-java:1.4.9"
json = "org.json:json:20230618"
kaml = "com.charleskorn.kaml:kaml:0.55.0"
org-eclipse-jgit = "org.eclipse.jgit:org.eclipse.jgit:6.6.1.202309021850-r"
commons-io = "commons-io:commons-io:2.13.0"
javaparser-core = "com.github.javaparser:javaparser-core:3.25.5"
commons-math = "org.apache.commons:commons-math3:3.6.1"
slf4j-api = "org.slf4j:slf4j-api:2.0.7"
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logback-core = { module = "ch.qos.logback:logback-core", version.ref = "logback" }
mockk = "io.mockk:mockk:1.13.7"
progressbar = "me.tongfei:progressbar:0.10.0"

[bundles]
kotlin-testing = [ "kotest-junit5-jvm", "kotest-assertions-core-jvm", "mockito-core" ]

[plugins]
dokka = "org.jetbrains.dokka:1.9.0"
gitSemVer = "org.danilopianini.git-sensitive-semantic-versioning:1.1.10"
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-qa = "org.danilopianini.gradle-kotlin-qa:0.29.2"
multiJvmTesting = "org.danilopianini.multi-jvm-test-plugin:0.5.5"
publishOnCentral = "org.danilopianini.publish-on-central:5.0.13"
taskTree = "com.dorongold.task-tree:2.1.1"
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
shadowJar = "com.github.johnrengelman.shadow:8.1.1"
